name: Docker
on:
  push:
    # tags:
    #   - 'ndn-tools-*'
  schedule:
    # twice a month
    - cron: '20 10 5,20 * *'
  workflow_dispatch:

permissions:
  attestations: write
  packages: write
  id-token: write

jobs:
  ndn-tools:
    uses: ./.github/workflows/docker-image.yml
    with:
      name: ndn-tools
